# Generated by Django 6.0.5 on 2026-05-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='posters/')),
                ('genre', models.CharField(choices=[('action', 'Action'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('sci-fi', 'Sci-Fi'), ('thriller', 'Thriller'), ('romance', 'Romance'), ('documentary', 'Documentary')], max_length=50)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('release_year', models.IntegerField()),
            ],
        ),
    ]
