# Generated by Django 6.0.5 on 2026-05-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='URL YouTube (ex: https://www.youtube.com/watch?v=xxx)', null=True),
        ),
    ]
